### ISSUE TITLE
The X tô hide a notification is dificult to click

### ISSUE THREAD

**Issue by jonasbrant** [exoplatform/exo-ios#251]
When you try to click to hide a notification the x bóton is difficult to select and you goes to the task .
![E12C6B2A-ED62-4748-8692-7115BB9F01B3](https://user-images.githubusercontent.com/11363238/235541578-d599c641-f286-425e-b247-1c97d92ec614.jpeg)

**Comment by ahamdi** [comment]
Hi @jonasbrant the notification drawer is part of the Meeds project, could you report this issue there . Thanks

**Comment by jonasbrant** [comment]
@ahamdi  in witch project should i include this issue, as it is exclusively happening in IOS app. Lookalike that X is in a position that is difficult to click in the cellphone screen and them when you click you go to the task o activities where in were marked

**Comment by ahamdi** [comment]
@jonasbrant I believe that the problem is also reproduced with Safari browser on mobile (not just using the Mobile app), right ?
If it is the case, you may open an issue in the Meeds project [github.com/meeds-io/meeds](https://github.com/Meeds-io/meeds/issues)

**Comment by ahamdi** [comment]
Issue recreated on Meeds project Meeds-io/meeds#937
